---
services:
  postgres:
    image: postgres:17.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: journal_user
      POSTGRES_DB: journal_db
      POSTGRES_PASSWORD: journal_pazzwerdz
    container_name: journal
